### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'is')

### ISSUE THREAD

**Issue by Zonalds** [grid-js/gridjs#1341]
**Describe the bug**
The table throws this error:

```
caught TypeError: Cannot read properties of undefined (reading 'is')
    at R (gridjs.module.js:1:8651)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at R (gridjs.module.js:1:9341)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at F (gridjs.module.js:1:7783)
    at T (gridjs.module.js:1:4229)
    at R (gridjs.module.js:1:9341)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at F (gridjs.module.js:1:7783)
    at T (gridjs.module.js:1:4229)
    at F (gridjs.module.js:1:7783)
    at T (gridjs.module.js:1:4229)
    at R (gridjs.module.js:1:9341)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at F (gridjs.module.js:1:7783)
    at T (gridjs.module.js:1:4229)
    at R (gridjs.module.js:1:9341)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at F (gridjs.module.js:1:7783)
    at T (gridjs.module.js:1:4229)
    at R (gridjs.module.js:1:9341)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at R (gridjs.module.js:1:9341)
    at F (gridjs.module.js:1:8056)
    at T (gridjs.module.js:1:4229)
    at F (gridjs.module.js:1:7783)
    at eval (gridjs.module.js:1:3564)
    at Array.some (<anonymous>)
    at I (gridjs.module.js:1:3470)
    at sentryWrapped (helpers.js:90:1)
R
```

**To Reproduce**
1. Install Gridjs on NextJs
2. Create a table that uses server-side pagination
3. Render and see error.

**Expected behavior**
No error, just render page

**Screenshots**
![image](https://user-images.githubusercontent.com/50281058/231863655-a97b5035-a1c4-49f4-805b-4073d1dae690.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave. Tried multiple Chrome and Edge too
 - Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (x86_64)](https://brave.com/latest/)

**Additional context**
The data is consistent and tends to render 1 out of 10 attempts

**Comment by Zonalds** [comment]
Update:


This to happen when I don't have a useQuery (apollo graphql client) call on the page which is a really strange thing. If I remove the useQuery call it throws the error.

**Comment by engineersamwell** [comment]
Please re-open, this is still an outstanding issue in 6.1.1.  I don't have time to put together a complete reproducer, but I can show the component I'm using in Qwik where it starts with [] data and then I populate it and pass that to the component which causes the problem:

```
// Parent component where the rows.values changes
      <GridTable columns={columns} data={rows.value} />

// GridTable component that renders the gridjs table, this is where the error randomly happens.
import { component$, useSignal, useVisibleTask$, noSerialize } from '@builder.io/qwik';
import { Grid } from 'gridjs';
import 'gridjs/dist/theme/mermaid.css';
import { TData, OneDArray, TColumn } from 'gridjs/dist/src/types';

type Props = {
  columns: OneDArray<TColumn> | string[];
  data?: TData;
};

export default component$<Props>((props) => {
  const tableRef = useSignal<HTMLElement>();
  const gridRef = useSignal<Grid>();
  const loading = useSignal(true);

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(
    ({ cleanup }) => {
      if (!gridRef.value) {
        const grid = noSerialize(
          new Grid({
            columns: props.columns,
            data: props.data,
            sort: true,
          }),
        );
        loading.value = false;

        grid?.render(tableRef.value as Element);
        gridRef.value = noSerialize(grid);
      }

      cleanup(() => {
        console.log('Destroying grid');
        gridRef.value?.destroy();
        gridRef.value = undefined;
      });
    },
    { strategy: 'document-idle' },
  );

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track }) => {
    track(() => props.data);
    console.log('Updating data', props.data?.length);
    gridRef.value
      ?.updateConfig({
        data: props.data,
      })
      .forceRender();
  });

  return (
    <>
      <div ref={tableRef} />
    </>
  );
});
```

**Comment by engineersamwell** [comment]
I know how to reproduce this now, this happens when passing a data array that contains non-string elements and then using `updateConfig` with new data and calling  `forceRender`.  For example if going from `['', 'a', 'b']` to `['', [], 'b']` or vice versa, it can cause that.  I figure this out when I mapped/joined the array to produce a string then the error went away.
